frontend/index.html, frontend/main.js, frontend/package.json, frontend/src/App.tsx, frontend/tsconfig.app.json, frontend/vite.config.ts, frontend/yarn.lock
#72 
electron 적용
| 기능 | 스크린샷 |
| electron 적용하여 웹앱 띄우기 |  ![image](https://github.com/user-attachments/assets/3ac247c6-ddab-4e67-bfa6-8609591dbe19)  |
- `concurrently`를 사용해 react 개발 서버를 여는 것과 electron 앱을 병렬 실행 하도록 했습니다.
- 이때, react 개발 서버가 열린 뒤에 electron 앱이 실행되어야 하므로 `wait-on`을 사용했습니다.
- electron은 Node.js와 크로미움 기반의 데스크톱 애플리케이션 개발 프레임워크입니다. 웹 기술을 사용하여 데스크톱 어플리케이션을 개발하는만큼 보안에 대한 주의가 필요하여, 나중에 보안 관련 설정을 추가적으로 해주어야 합니다.
=> [FE] electron+react 초기 설정 (#72)

backend/src/app.module.ts
[#77]
> 구현한 작업 내역
슬랙-깃 웹훅 연동
불필요 콘솔 제거
=> slack git 연동 테스트

.github/workflows/backend-deploy.yml
github actions 백엔드 자동 배포 설정 추가
.github/workflows/backend-deploy-yml 추가
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> chore: 백엔드 자동배포 설정 추가[#1]

.github/workflows/backend-deploy.yml, .gitignore, backend/docker-compose.yml, backend/src/config/typeorm.config.ts, nginx.conf
백엔드 아키텍처 재구성
docker-compose 수정 및 NestJS와 PostgreSQL 연결
> 구현한 작업 내역
| 기능 | 스크린샷 |
- [] 파일 혹은 폴더 추가
=> [BE] docker-compose 수정

backend/src/bet/bet.gateway.ts
[#98]
> 구현한 작업 내역
대기창에 있는 사람들은 베팅방에 참여하지 않지만 베팅방에 참여한 사람들의 목록을 실시간으로 확인가능하도록 수정
- 베팅방에 참여한 사용자와 대기창에서 베팅방을 조회하는 사용자를 분리
- 특정 방의 사용자 목록을 실시간으로 받을 수 있도록 하기 위해, id를 이용한 waiting 룸을 만들어 이벤트 발행 범위를 특정함.
=> [BE] 대기창에서 참여자 목록 실시간 조회 로직 오류 수정

backend/src/bet/bet.gateway.ts
[#98]
> 구현한 작업 내역
베팅 소켓I/O 대기창과 베팅창 참여자를 하나의 룸으로 관리
=> [BE] 베팅 소켓I/O 대기창과 베팅창 참여자 통합 관리

backend/src/bet/bet.gateway.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.module.ts
> 구현한 작업 내역
- 실시간 채팅 소켓 I/O 구현
- 실시간 베팅 joinRoom시 파라미터 변경
=> [BE] 실시간 채팅 소켓 I/O 구현

backend/package.json, backend/pnpm-lock.yaml, backend/src/app.module.ts, backend/src/bet/bet.gateway.ts, backend/src/bet/bet.module.ts, backend/src/config/redis.config.ts, backend/src/utils/redis-manager.module.ts, backend/src/utils/redis.manager.ts
> 구현한 작업 내역
- 실시간 베팅 데이터 관리를 위한 레디스 도입
- nestjs-redis 간 연결 설정
- fetchRoomUsers 반환 배열에 joinAt 추가
- 소켓 테스트 완료
=> [BE] 실시간 베팅 소켓 I/O 레디스 연결

backend/nest-cli.json, backend/package.json, backend/pnpm-lock.yaml, backend/src/bet/bet.gateway.ts, backend/src/chat/chat.gateway.ts, backend/tsconfig.json, shared/schemas/bet/socket/request.ts, shared/schemas/chat/socket/reponse.ts, shared/schemas/chat/socket/request.ts, shared/schemas/shared.ts
nest js에서 shared의 zod 스키마를 import 할 수 있도록 설정
bet, chat의 소켓 통신의 request에 zod 적용
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - 소켓통신 zod 적용

backend/package.json, pnpm-lock.yaml, shared/schemas/shared.ts
[#110]
chat의 sendMessage 이벤트가 제대로 작동하지 않는 문제
sendMessageRequestSchema의 message가 string이 아닌 object 타입으로 선언되어 있었음 -> 스키마 수정
uuid 패키지 추가
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> fix: chat 모듈의 sendMessageRequestSchema 수정

backend/src/chat/chat.gateway.ts, backend/src/utils/filters/global-ws-exception-filter.ts, backend/src/utils/guards/authenticated-guard.ts
에러 처리 filter 추가 -> 에러 컨벤션 필요
다만 catch 되는 exception이 구체적인 타입 없이 object로 들어오는 경우가 있다는 점을 유의
인증 guard 추가
인증 로직 구현 가능, 로그인 기능 구현 후 가능할 듯
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - 소켓 통신에 대한 에러, 인증 처리

frontend/package.json, frontend/src/features/waiting-room/cancel-voting/ui/CancleVottingButton.tsx, frontend/src/features/waiting-room/start-voting/ui/StartVotingButton.tsx, frontend/src/main.tsx, frontend/src/pages/WaitingRoom/ActionButtons.tsx, frontend/src/pages/WaitingRoom/VotingStatusCard.tsx, frontend/src/shared/hooks/use-socket-io.tsx, frontend/src/widgets/chat/ChatInput/ui/InputBar.tsx, frontend/src/widgets/chat/ChatMessages/index.tsx, frontend/vite.config.ts, pnpm-lock.yaml, shared/index.ts
배포 시 vite config 설정을 제대로 설정 해놓지 않아서 배포시에 사이트에 오류가 발생하고 있습니다.
- 채팅을 진행할 수 있는 방에 대한 레이아웃 추가
- 채팅을 위한 소켓 연결
- socket.io 를 사용하기 위한 hook 작성
=> [FE] 채팅 창에 대한 레이아웃 추가 및 build 시 정적 파일에 대한 경로가 제대로 작성되지 않아서 발생하는 문제 수정 중

backend/src/bet-room/bet-room.controller.ts, backend/src/bet-room/bet-room.service.ts, backend/src/bet-room/dto/create-bet-room.dto.ts, backend/src/bet-room/dto/update-bet-room.dto.ts
> 구현한 작업 내역
베팅방 수정 API 생성
- update-bet-room.dto 옵셔널로 설정
- 클라이언트에서 수정된 필드만 전송하도록 구현
example
```js
{
"channel": {
"title": "기아 vs 삼성 승부 예측22"
}
}
```
```js
{
"channel": {
"options": {
"option1": "기아222"
},
"settings": {
"duration": 300
}
}
}
```
=> [BE] 베팅방 수정 API 구현

backend/src/bet-result/bet-result.entity.ts, backend/src/bet-result/bet-result.module.ts, backend/src/bet-result/bet-result.repository.ts, backend/src/bet-room/bet-room.controller.ts, backend/src/bet-room/bet-room.entity.ts, backend/src/bet-room/bet-room.module.ts, backend/src/bet-room/bet-room.service.spec.ts, backend/src/bet-room/bet-room.service.ts, backend/src/bet/bet.gateway.ts, backend/src/utils/redis.manager.ts
> 구현한 작업 내역
베팅방 종료 API 제공
- DB 접근 후 bet 상태 finished 업데이트
- bet result 테이블에 베팅 결과 저장
- 승리 배당 계산 메서드 구현
- 레디스에서 해당 채널 관련 정보 삭제
=> [BE] 베팅방 종료 API 구현

backend/src/auth/user.controller.ts, backend/src/config/swagger.config.ts, nginx.conf
restapi에 대해 /api/docs와 같이 `/api`(baseurl)가 정상적으로 적용되지 않음을 확인
nginx의 proxy_pass에 `/api`를 붙여 전달하도록 수정
nestjs에서 모든 엔드포인트에 `/api`를 붙이도록 수정
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - 엔드포인트 연결 문제 수정

frontend/src/features/create-vote/model/helpers/formatData.ts, frontend/src/features/create-vote/model/store.ts, frontend/src/features/create-vote/model/types.ts, frontend/src/features/create-vote/ui/CreateVotePage.tsx, frontend/src/index.css
#119 
- 타이머 설정 기능
- 최소 베팅 금액 설정 기능
- Icon 리렌더링 이슈 해결: 메모이제이션 사용
- API 요청을 위한 데이터 포매팅 함수 구현
- inner-shadow 적용 제대로 안 되어있던 것 개선
- 오리 아이콘 잘림 이슈 해결
| 기능 | 스크린샷 |
| CSS 수정 전 | ![스크린샷 2024-11-19 오전 12 52 45](https://github.com/user-attachments/assets/85fe51ab-16e2-4937-af30-818eae052937) |
| CSS 수정 후 | ![스크린샷 2024-11-19 오전 1 01 00](https://github.com/user-attachments/assets/65acc921-e8ce-44d3-8cd2-8618e019154d)|
- 현재 API 명세가 중첩 객체로 되어있습니다. FormData는 중첩객체를 구현하기에 너무 번거로워서 FormData 사용 대신 state 값을 사용하는 것으로 변경해주었습니다.
=> [FE] 승부예측생성페이지 퍼블리싱 완료/기능구현/코드리팩터링/성능최적화

frontend/src/features/betting-page-admin/index.tsx, frontend/src/features/betting-page-admin/ui/BettingStatsDisplay.tsx, frontend/src/features/betting-page/BettingStatsDisplay.tsx, frontend/src/features/chat/hook/use-chat.tsx, frontend/src/features/chat/index.tsx, frontend/src/features/chat/provider/ChatProvider.tsx, frontend/src/features/chat/ui/ChatInput/ui/EmoticonButton.tsx, frontend/src/features/chat/ui/ChatInput/ui/InputBar.tsx, frontend/src/features/chat/ui/ChatMessages/index.tsx, frontend/src/features/chat/ui/ChatMessages/ui/MessageList.tsx, frontend/src/features/predict-detail/index.tsx, frontend/src/features/predict-detail/ui/GuestFooter.tsx, frontend/src/features/predict-detail/ui/UserFooter.tsx, frontend/src/routeTree.gen.ts, frontend/src/routes/betting-page.tsx, frontend/src/routes/login.tsx, frontend/src/routes/predict-detail.$userType.tsx, frontend/src/shared/components/ProgressBar/index.tsx, frontend/src/shared/icons/TimerIcon.tsx, frontend/tailwind.config.js
[#9]
- 채팅이 소켓을 이용하여 리스트가 업데이트 되게 수정
- 채팅이 업데이트 될 경우 스크롤이 아래로 고정되게 끔 수정
- 어드민 페이지 추가
- 동적 param을 이용하여 컴포넌트가 변경되게 끔 코드 수정
=> [FE] 소켓을 이용하여 채팅이 업데이트 되게 수정 및 어드민 페이지 추가

frontend/src/features/create-vote/model/api.ts, frontend/src/features/create-vote/model/store.ts
[#119]
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [FE] 채팅 생성 API 연동

backend/src/auth/user.service.ts, backend/src/bet-room/bet-room.controller.ts, backend/src/bet-room/bet-room.service.ts
> 구현한 작업 내역
베팅방 조회 API 구현
유저 서비스에서 user의 duck number형으로 변경
=> [BE] 베팅방 조회 API

backend/src/app.module.ts, backend/src/bet-result/bet-result.controller.ts, backend/src/bet-result/bet-result.entity.ts, backend/src/bet-result/bet-result.module.ts, backend/src/bet-result/bet-result.repository.ts, backend/src/bet-result/bet-result.service.ts, backend/src/bet-room/bet-room.controller.ts, backend/src/bet-room/bet-room.entity.ts, backend/src/bet-room/bet-room.service.ts
> 구현한 작업 내역
- 베팅 결과 조회 API 구현
- 베팅방 조회 시 서비스 단에서 데이터 포맷하도록 리팩토링
- BetRoom-Betresult 일대일 관계에 맞게 엔티티 타입 수정(배열 형태 -> 단일 객체 형태)
=> [BE] 베팅 결과 조회 API 구현

backend/src/auth/user.repository.ts, backend/src/auth/user.service.ts, backend/src/bet-result/bet-result.controller.ts, backend/src/bet-room/bet-room.controller.ts, backend/src/bet-room/bet-room.service.ts, backend/src/bet/bet.gateway.ts, shared/schemas/shared.ts
> 구현한 작업 내역
1. bet-room / bet-result 컨트롤러에 JWT 인증 및 userID 추출
2. bet.gateway.ts에 jwt 인증 및 userID 추출
3. bet.gateway.ts JoinRoom 스키마에서 닉네임 제거
4. bet.gateway.ts 에러 컨벤션
=> [BE] 컨트롤러 소켓에 JWT 기능 병합

frontend/public/mockServiceWorker.js, frontend/src/features/betting-page/index.tsx, frontend/src/features/chat/index.tsx, frontend/src/features/chat/ui/ChatHeader/index.tsx, frontend/src/features/chat/ui/ChatHeader/ui/PredictButton.tsx, frontend/src/features/chat/ui/ChatInput/index.tsx, frontend/src/features/chat/ui/ChatInput/ui/InputBar.tsx, frontend/src/features/chat/ui/ChatMessages/index.tsx, frontend/src/features/chat/ui/ChatMessages/ui/MessageList.tsx, frontend/src/index.css, frontend/src/routeTree.gen.ts, frontend/src/routes/betting-page.tsx, frontend/src/routes/demo-login.tsx, frontend/src/shared/hooks/use-effect-once.tsx, frontend/src/shared/hooks/use-socket-io.tsx
=> [FE] - 메세지 최적화 진행 중

nginx.conf
[#24]
> 구현한 작업 내역
cors 설정에 메서드 추가
=> [BE] 개발 환경을 위한 임시 nginx 설정

backend/src/bet/bet.gateway.ts
[#24]
> 구현한 작업 내역
소켓 연결 에러 이벤트 발행
=> [BE] 소켓 연결 에러이벤트 발행

backend/src/bet/bet.gateway.ts
[#24]
> 구현한 작업 내역
소켓 엑세스 토큰 추출 auth.token로 변경
=> [BE] 소켓 엑세스 토큰 추출 auth.token로 변경

backend/src/bet-room/bet-room.service.ts, backend/src/bet/bet.gateway.ts
> 구현한 작업 내역
베팅 소켓 토큰 추출 변수 에러 수정
투표 초대 URL 생성
=> [BE] 소켓 토큰 추출 경로 수정 및 베팅 초대 URL 생성

frontend/src/features/create-vote/model/store.ts
=> [FE] 투표 생성 후 리다이렉트 되게 끔 로직 추가

frontend/src/features/chat/ui/ChatInput/ui/InputBar.tsx, frontend/src/features/chat/ui/ChatMessages/index.tsx, frontend/src/features/chat/ui/ChatMessages/ui/MessageList.tsx
[#54]
맥 환경에서 키보드를 칠 경우 같은 문자가 두번 입력되는 문제 수정
=> [FE] 맥 환경에서 키보드를 칠 경우 같은 문자가 두번 입력되는 문제 수정

frontend/src/features/waiting-room/ui/SharedLinkCard.tsx, frontend/vite.config.ts
경로가 복사 되지 않고 복사된 url로 들어갈 수 없는 문제 수정 중
=> [FE] 경로가 복사 되지 않고 복사된 url로 들어갈 수 없는 문제 수정 중

backend/src/auth/user.controller.ts, backend/src/auth/user.service.ts, backend/src/utils/redis.manager.ts
- 비회원 로그인의 에러코드 변경
- 닉네임 중복 검사 시, redis의 비회원 닉네임도 검사
- 닉네임 중복검사 API의 메소드를 GET으로 변경
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - 비회원 로그인 및 닉네임 중복검사 수정

backend/src/auth/dto/upgrade-guest.dto.ts, backend/src/auth/user.controller.ts, backend/src/auth/user.service.ts, backend/src/utils/redis.manager.ts, shared/schemas/users/request.ts
- 로그아웃 API 구현
- 비회원 -> 회원 전환 API 구현 중
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - 로그아웃 API 구현

backend/src/bet-room/bet-room.service.ts, backend/src/bet/bet.gateway.ts
> 구현한 작업 내역
베팅 시작 시 startBetting 이벤트 발행
베팅룸 취소 시 cancelWaitingRoom 이벤트 발행
=> [BE] 베팅 시작, 취소 시 소켓 이벤트 발행

backend/src/auth/user.controller.ts, backend/src/auth/user.repository.ts
[#182]
> 구현한 작업 내역
개발 환경을 위해 엑세스 토큰 유효기간 임시 변경 (24h)
=> [BE] 토큰 유효기간 임시 변경

backend/src/auth/user.service.ts, backend/src/utils/redis.manager.ts
- 회원가입 API에서 "익명의" 키워드 검사 수행
- 비회원 로그인 API에서 "익명의" 키워드 검사 수행
-  비회원 로그인 API에서 비회원 닉네임 중복 검사
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - 닉네임 중복 관련 로직 추가

backend/src/config/redis.config.ts, backend/src/utils/redis.manager.ts, nginx.conf
- WSS 이슈로 인해 nginx의 SSL인증 롤백
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - SSL 인증 롤백

backend/src/bet-room/bet-room.service.ts, backend/src/bet/bet.gateway.ts, backend/src/utils/redis.manager.ts
> 구현한 작업 내역
참여자 닉네임을 레디스 list 자료 구조로 관리
lpush를 이용해 최신 순으로 정렬
소켓 disconnect 시, 배열에서 제거
=> [BE] 베팅 참여자 레디스 list로 관리

frontend/src/features/betting-page/index.tsx, frontend/src/features/betting-page/ui/BettingContainer.tsx, frontend/src/features/betting-page/utils/bettingOdds.ts, frontend/src/features/waiting-room/provider/WaitingRoomProvider.tsx, frontend/src/features/waiting-room/ui/ParticipantsList.tsx, frontend/src/features/waiting-room/ui/WaitingRoomHeader/EditFormStatusForm.tsx, frontend/src/features/waiting-room/ui/WaitingRoomHeader/VotingStatusCard.tsx, frontend/src/routes/betting_.$roomId.waiting.tsx, frontend/vite.config.ts
- https 서버를 사용하기 위해서 바꿨던 설정들을 다시 http를 사용하여 이용하게 끔 수정
- 같은 용도로 사용이 되지만 다른 파일에서 다른 변수명으로 사용이 되고 있던 문제 수정
- 타이머 기능 구현 중
=> [FE] - HTTPS에서 작동하게끔 수정 했던 설정을 다시 복구 및 오류 수정

frontend/src/app/provider/UserProvider.tsx, frontend/src/features/betting-page/hook/use-betting-socket.ts, frontend/src/features/betting-page/index.tsx, frontend/src/features/betting-page/model/schema.ts, frontend/src/features/betting-page/ui/BettingContainer.tsx, frontend/src/features/betting-page/ui/BettingForm.tsx, frontend/src/features/betting-page/ui/BettingInput/index.tsx, frontend/src/features/betting-page/ui/PercentageDisplay.tsx, frontend/src/features/betting-page/utils/bettingOdds.ts, frontend/src/index.css, frontend/src/shared/components/Dialog/context.tsx, frontend/src/shared/hooks/use-session-storage.ts
- 배팅 진행 시 남은 시간을 표기할 수 있는 타이머 기능 추가
- 배팅 페이지 리펙토링 진행 중
- 세션 스토리지에서 사용할 데이터의 보안성을 높이기 위한 작업 수행 중
=> [FE] 배팅 진행 시 남은 시간을 표기할 수 있는 타이머 기능 추가

backend/src/bet-room/bet-room.controller.ts, backend/src/bet-room/bet-room.service.ts, backend/src/bet/bet.entity.ts, backend/src/bet/bet.module.ts, backend/src/bet/bet.repository.ts, backend/src/utils/redis.manager.ts
> 구현한 작업 내역
- redis 삽입 동작 시 트랜잭션 처리
- bet entity status 필드 추가
- 베팅 내역 DB 업데이트
- 정산 메서드 리팩토링
- 베팅방 조회 시 방장 여부 확인
=> [BE] DB에서 베팅 내역 상태 관리

backend/src/auth/user.module.ts, backend/src/auth/user.service.ts, backend/src/utils/db.manager.module.ts, backend/src/utils/db.manager.ts
[#172]
- DBManager setBet 메소드 추가
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - DBManager setBet 메소드 추가

backend/src/bet/bet.gateway.ts
[#201]
> 구현한 작업 내역
사용자 베팅 시 오리코인 금액 체크 메서드 수정
=> [BE] 사용자 오리코인 음수 체크 로직 수정

frontend/src/features/betting-page/api/getBettingRoomInfo.ts, frontend/src/features/betting-page/api/getUserInfo.ts, frontend/src/features/betting-page/hook/useBettingRoomConnection.ts, frontend/src/features/betting-page/hook/useBettingRoomInfo.ts, frontend/src/features/betting-page/index.tsx, frontend/src/features/betting-page/provider/BettingProvider.tsx, frontend/src/features/betting-page/ui/BettingContainer.tsx, frontend/src/features/betting-page/ui/BettingFooter.tsx, frontend/src/features/betting-page/ui/BettingHeader.tsx, frontend/src/features/betting-page/ui/BettingInput/index.tsx, frontend/src/features/betting-page/ui/BettingStatsDisplay.tsx, frontend/src/features/betting-page/ui/BettingTimer.tsx, frontend/src/features/betting-page/ui/PercentageDisplay.tsx, frontend/src/features/betting-page/utils/placeBetting.ts, frontend/src/features/chat/provider/ChatProvider.tsx, frontend/src/features/decide-betting-result/index.tsx, frontend/src/features/my-page/index.tsx, frontend/src/features/waiting-room/ui/AdminFooter/StartVotingButton.tsx, frontend/src/features/waiting-room/ui/MemberFooter/index.tsx, frontend/src/index.css, frontend/src/routeTree.gen.ts, frontend/src/routes/betting_.$roomId.vote.decide.tsx, frontend/src/routes/betting_.$roomId.vote.tsx, frontend/src/routes/betting_.$roomId.vote.voting.tsx, frontend/src/shared/components/ProgressBar/index.tsx, frontend/src/shared/icons/TimerIcon.tsx
=> [FE] 투표 페이지 완성 및 결과 페이지 작성 중

frontend/src/features/betting-page/api/endBetroom.ts, frontend/src/features/betting-page/ui/BettingInput/index.tsx, frontend/src/features/decide-betting-result/index.tsx, shared/schemas/bet/socket/response.ts
=> [FE] 승부 예측 결과를 결정 짓는 페이지 추가

frontend/src/features/betting-page/ui/BettingSharedLink.tsx, frontend/src/features/betting-page/ui/BettingStatsDisplay.tsx, frontend/src/features/predict-detail/index.tsx, frontend/src/features/predict-detail/ui/Bettingstatistics.tsx, frontend/src/routes/betting_.$roomId.vote.detailResult.tsx, frontend/src/routes/betting_.$roomId.waiting.tsx
=> [FE] 결과 상세 페이지 업데이트

backend/src/bet-room/bet-room.service.ts
setTimeout 내부에서 발생하는 에러 처리
자동 환불 제거
=> [BE] 환불 setTimeout 에러 캐치

backend/src/bet-room/bet-room.service.ts
> 구현한 작업 내역
setTimeout 메서드 분리
자동 환불 기능 제거
=> [BE] 자동 환불 기능 비활성화

backend/package.json, backend/src/bet/bet.gateway.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.module.ts, backend/src/main.ts, backend/src/utils/redis-io-adapter.ts
=> [BE] 레디스 어댑터 적용

frontend/package.json, frontend/src/app/provider/UserProvider.tsx, frontend/src/features/betting-page-admin/index.tsx, frontend/src/features/betting-page/model/var.ts, frontend/src/features/betting-page/provider/BettingProvider.tsx, frontend/src/features/betting-page/ui/BettingContainer.tsx, frontend/src/features/betting-page/ui/BettingFooter.tsx, frontend/src/features/betting-page/ui/BettingInput/index.tsx, frontend/src/features/betting-page/utils/placeBetting.ts, frontend/src/features/chat/ui/ChatHeader/ui/PredictButton.tsx, frontend/src/features/chat/ui/ChatMessages/ui/MessageList.tsx, frontend/src/features/login-page/ui/LoginPage.tsx, frontend/src/features/login-page/ui/components/GuestLoginForm.tsx, frontend/src/features/login-page/ui/components/LoginForm.tsx, frontend/src/features/waiting-room/index.tsx, frontend/src/features/waiting-room/provider/WaitingRoomProvider.tsx, frontend/src/features/waiting-room/ui/AdminFooter/StartVotingButton.tsx, frontend/src/features/waiting-room/ui/MemberFooter/index.tsx, frontend/src/features/waiting-room/ui/ParticipantsList.tsx, frontend/src/routes/betting.index.tsx, frontend/src/routes/betting_.$roomId.vote.tsx, frontend/src/routes/betting_.$roomId.vote.voting.tsx, frontend/src/shared/components/Loading/index.tsx, frontend/src/shared/components/RootSideBar/index.tsx, pnpm-lock.yaml
- 페이지 이동 간에 생기는 상태 불일치로 인한 여러 오류 수정 중
=> [FE] 페이지 이동 간에 생기는 상태 불일치로 인한 여러 오류 수정 중

frontend/src/features/betting-page-admin/index.tsx, frontend/src/features/betting-page/provider/BettingProvider.tsx, frontend/src/features/betting-page/ui/BettingContainer.tsx, frontend/src/features/betting-page/ui/BettingFooter.tsx, frontend/src/features/betting-page/ui/BettingInput/index.tsx, frontend/src/features/betting-page/utils/placeBetting.ts, frontend/src/routes/betting_.$roomId.vote.admin.tsx, frontend/src/routes/betting_.$roomId.vote.tsx, frontend/src/shared/components/RootHeader/index.tsx
[#61]
- 관리자 페이지에 제대로 접근이 안되는 문제 수정
- 배팅 페이지의 내역이 제대로 업데이트가 되지 않던 문제 수정
- 상단의 닉네임을 보여주는 내용이 최신 서버 내용을 반영하고 있지 않던 문제 수정
=> [FE] 관리자 페이지에 제대로 접근이 안되는 문제 수정

backend/src/auth/user.module.ts, backend/src/auth/user.service.ts
- 비회원 로그아웃 시, redis에서 정보를 삭제하지 않도록 수정
- 액세스 토큰의 유효기간을 1시간 -> 24시간으로 수정
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - 로그아웃 및 액세스 토큰 유효기간 수정

backend/src/bet/bet.service.ts
[#223]
> 구현한 작업 내역
베팅 시 유저 코인 DB 업데이트 비회원은 제외
=> [BE] 베팅 시 유저 코인 업데이트 비회원 제외

backend/src/bet/bet.controller.ts, backend/src/bet/bet.gateway.ts, backend/src/bet/bet.service.ts, backend/src/utils/redis.manager.ts
> 구현한 작업 내역
내 베팅 내역(betAmount, selectOption) 조회 API 구현
베팅 시작 시 레디스의 유저 해시에서 초기화 정보 추가 (betAmount, selectOption)
=> [BE] 내 베팅 내역 조회 API 구현

backend/src/auth/user.controller.ts, backend/src/auth/user.entity.ts, backend/src/auth/user.service.ts, backend/src/utils/redis.manager.ts
- DB users 테이블에 realDuck 필드 추가
- 오리 구매 시, redis의 user 닉네임이 null이 되는 문제 수정
> 구현한 작업 내역
| 기능 | 스크린샷 |
=> [BE] - realDuck 필드 추가 및 버그 수정

frontend/src/features/login-page/ui/components/Logout.tsx, frontend/src/features/my-page/index.tsx, frontend/src/routeTree.gen.ts, frontend/src/routes/betting.index.tsx, frontend/src/routes/login.tsx, frontend/src/routes/my-page.tsx, frontend/src/routes/require-bettingRoomId.tsx
=> [FE] 로그인 로그아웃이 제대로 되지 않던 문제 수정

frontend/src/features/betting-page-admin/index.tsx, frontend/src/features/betting-page-admin/model/api.ts, frontend/src/features/betting-page/hook/useBettingRoomConnection.ts, frontend/src/features/betting-page/index.tsx, frontend/src/features/betting-page/ui/BettingFooter.tsx, frontend/src/features/betting-page/ui/BettingHeader.tsx, frontend/src/features/betting-page/utils/placeBetting.ts, frontend/src/features/chat/index.tsx, frontend/src/features/chat/ui/ChatHeader/ui/PredictButton.tsx, frontend/src/features/predict-detail/index.tsx, frontend/src/features/predict-detail/model/api.ts, frontend/src/features/predict-detail/ui/AdminBettingResult.tsx, frontend/src/features/predict-detail/ui/Bettingstatistics.tsx, frontend/src/features/predict-detail/ui/UserBettingResult.tsx, frontend/src/features/waiting-room/ui/AdminFooter/StartVotingButton.tsx, frontend/src/routes/betting_.$roomId.vote.admin.tsx, frontend/src/routes/betting_.$roomId.vote.voting.tsx, frontend/src/shared/api/responseBettingRoomInfo.ts, frontend/src/shared/hooks/useBettingRoomInfo.ts, frontend/src/shared/hooks/usePreventLeave.ts, frontend/src/shared/lib/loader/useBetRoomLoader.ts
=> [FE] '배팅'으로 되어있던 것을 '베팅'으로 수정

frontend/src/features/betting-page-admin/index.tsx, frontend/src/features/betting-page/hook/useBettingRoomConnection.ts, frontend/src/features/betting-page/index.tsx, frontend/src/features/betting-page/ui/BettingInput/index.tsx, frontend/src/features/betting-page/ui/TotalBettingDisplay.tsx, frontend/src/features/betting-page/utils/placeBetting.ts, frontend/src/features/chat/ui/ChatMessages/index.tsx, frontend/src/features/create-vote/model/store.ts, frontend/src/features/login-page/ui/components/GuestLoginForm.tsx, frontend/src/features/login-page/ui/components/LoginForm.tsx, frontend/src/features/my-page/index.tsx, frontend/src/features/predict-detail/index.tsx, frontend/src/features/waiting-room/ui/WaitingRoomHeader/EditFormStatusForm.tsx, frontend/src/routes/betting.index.tsx, frontend/src/routes/betting_.$roomId.vote.resultDetail.tsx, frontend/src/routes/betting_.$roomId.waiting.tsx, frontend/src/routes/create-vote.tsx, frontend/src/shared/hooks/useSessionStorage.ts, frontend/src/shared/hooks/useSocketIo.tsx, frontend/src/shared/lib/auth/guard.ts, shared/schemas/users/response.ts
=> [FE] 자잘한 오류 수정
